# Settings for Selenium WebDriver used for browser testing.
selenium:
  active: false

  # Set type to LOCAL for running locally, and to REMOTE, to run on a remote
  # webdriver.  Default is LOCAL
  #type: LOCAL
  type: REMOTE


  # Set to true, to reuse the same browser.  Set to false, to use a fresh browser
  # instance each time.  If set to a number, this  would determine whether the browser
  # session should be discarded after a certain time period.
  # Default is 'true'
  reusebrowser: true

  threaded: false

  # Terminate Selenium after all tests have run. Disabling this can be helpful
  # during debugging.  In operation you normally want to keep this to clean up
  # after tests.
  shutdown_hook: true

  # Take screenshot of browser on error.
  take_screenshot: true
  # Take reference screenshot upon encountering a new page.
  take_reference_screenshot: true

  #annotate_screenshot: true

  # remote_url is required if type=REMOTE.  Set this to point at the Remote Webdriver
  # connection string.
  #remote_url: http://url.to.seleniumgrid:4444/wd/hub

  # Browser can be the following options.
  # ANDROID, CHROME, FIREFOX, HTMLUNIT, HTMLUNITWITHJS,
  # INTERNETEXPLORER, IPAD, IPHONE, OPERA, SAFARI
  desired_capabilities: {}
  browser: FIREFOX